### ISSUE TITLE
ERROR MEENU CONFIGURATION 

### ISSUE THREAD

**Issue by davide92br** [werdeil/pibooth#73]
hello, I installed the pibooth but when I press ESC to enter the configuration menu closes everything and in the terminal I receive

pi@raspberrypi:~ $ pibooth
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Starting the photo booth application...
[ WARNING ] pibooth           : No printer found (nothing defined in CUPS)
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 577, in main
    app.main_loop()
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 519, in main_loop
    menu = PiConfigMenu(self.window.surface, self.config)
  File "/usr/local/lib/python3.7/dist-packages/pibooth/config/menu.py", line 35, in __init__
    pgmfonts.FONT_FRANCHISE,
AttributeError: module 'pygameMenu.fonts' has no attribute 'FONT_FRANCHISE'

how can i fix it? i use a raspberry pi3 b+ with the latest version of raspian

**Comment by anxuae** [comment]
Fixed on v1.1.0
