### ISSUE TITLE
pibooth won't start - pygame.error: video system not initialized

### ISSUE THREAD

**Issue by dsheard** [werdeil/pibooth#80]
Getting the following issue when running pibooth. Have wiped my SD and started from scratch but still the same issue.

```
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Starting the photo booth application...
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 711, in main
    app = PiApplication(config)
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 392, in __init__
    pygame.event.set_blocked(pygame.MOUSEMOTION)
pygame.error: video system not initialized
```

**Comment by dsheard** [comment]
Camera was not working! Fixed

**Comment by dsheard** [comment]
Correction: still does this when running over ssh. Have to open VNC to get it working.

**Comment by anxuae** [comment]
Hi @dsheard,

I think that pygame display can not be started over ssh. You need a display plugged to your Raspberry Pi.

anxuae
