### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bpw23** [werdeil/pibooth#99]
Tried to install with `sudo pip3 install pibooth[dslr]`

Console output:
```Complete output from command python setup.py egg_info:
    ERROR: command "pkg-config --modversion libgphoto2" failed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rdm_o440/gphoto2/setup.py", line 38, in <module>
        cmd, stderr=FNULL, universal_newlines=True).split('.')
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pkg-config', '--modversion', 'libgphoto2']' returned non-zero exit status 1.
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rdm_o440/gphoto2/
```

System:
Raspi3B+ with raspian buster
software completly updated

**Comment by bpw23** [comment]
The obove problem is
`` Failed building wheel for Pillow``
and can be solved by a previous
```sudo apt-get install libjpeg-dev```


But if i now start 
```
pibooth
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
[ INFO    ] pibooth           : Generate the configuration file in '/home/pi/.config/pibooth/pibooth.cfg'
[ INFO    ] pibooth           : Generate the translation file in '/home/pi/.config/pibooth/translations.cfg'
[ INFO    ] pibooth           : Starting the photo booth application...
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 741, in main
    app = PiApplication(config)
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 447, in __init__
    config.getboolean('CAMERA', 'delete_internal_memory'))
  File "/usr/local/lib/python3.7/dist-packages/pibooth/controls/camera/__init__.py", line 37, in get_camera
    raise EnvironmentError("Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected")
OSError: Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected
```

A gphoto2 suppurted camera via usb is used

**Comment by bpw23** [comment]
Solved
